# Generated by Django 5.0.1 on 2024-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.URLField(default='https://i.pinimg.com/564x/c0/27/be/c027bec07c2dc08b9df60921dfd539b.jpg'),
        ),
    ]
