# Generated by Django 5.0.1 on 2024-03-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_profileimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
